### ISSUE TITLE
How would i use this libary

### ISSUE THREAD

**Issue by DoorsDev** [aelyo-softworks/Wice#1]
Hi.
Im a complete Wice noob but i wanna use it with my net6-windows7.0 project
How can i do that? I tried submoduling but it dosent work.
Thank you, ItsRedly

**Comment by smourier** [comment]
Hi,

As specified in the home page, this won't work with Windows 7, only  Windows 10 version 1809 minimal ("Redstone 5").
But it works fine with .NET 6.

**Comment by DoorsDev** [comment]
Ook lol. Thank you!
