### ISSUE TITLE
New WiceCore.Samples.Gallery use too much Memory

### ISSUE THREAD

**Issue by sgf** [aelyo-softworks/Wice#10]
old Wice.Samples.Gallery.exe old max  memory useage=50mb
but new WiceCore.Samples.Gallery.zip max  memory useage =170mb

and the Microsoft.Windows.SDK.NET.dll too big

If possible, can it be made more modular and the size reduced to less than 1mb? After all, the zip looks obviously does not carry a .net runtime.

I believe that they must have carried most of the il code that not need be executed.

**Comment by smourier** [comment]
About memory usage, I see around 50M for the .NET Framework (note it's not "old", it just targets another version of .NET) version, and around 70-80M for the .NET Core version, but this is unrelated to the size of binaries, it's managed by .NET.

As for Microsoft.Windows.SDK.NET.dll it comes from .NET core so there's nothing I can do about that.

I have no plan for making this modular, you can try to trim the code or use AOT (.NET 8) but I don't think it will work as it uses lots of interop and many scenarios are unsupported with this. But it certainly won't fit in 1Mb anyway

**Comment by sgf** [comment]
> About memory usage, I see around 50M for the .NET Framework (note it's not "old", it just targets another version of .NET) version, and around 70-80M for the .NET Core version, but this is unrelated to the size of binaries, it's managed by .NET.
> 
> As for Microsoft.Windows.SDK.NET.dll it comes from .NET core so there's nothing I can do about that.
> 
> I have no plan for making this modular, you can try to trim the code or use AOT (.NET 8) but I don't think it will work as it uses lots of interop and many scenarios are unsupported with this. But it certainly won't fit in 1Mb anyway

If you click on the tab page on the left, you will find that the memory usage of the core version will immediately increase. If you click a few more, it will immediately exceed 100.

**Comment by Charltsing** [comment]
![1](https://github.com/aelyo-softworks/Wice/assets/19963715/6a332f22-8323-4a71-9657-4ec4755509ef)

**Comment by smourier** [comment]
> > About memory usage, I see around 50M for the .NET Framework (note it's not "old", it just targets another version of .NET) version, and around 70-80M for the .NET Core version, but this is unrelated to the size of binaries, it's managed by .NET.
> > As for Microsoft.Windows.SDK.NET.dll it comes from .NET core so there's nothing I can do about that.
> > I have no plan for making this modular, you can try to trim the code or use AOT (.NET 8) but I don't think it will work as it uses lots of interop and many scenarios are unsupported with this. But it certainly won't fit in 1Mb anyway
> 
> If you click on the tab page on the left, you will find that the memory usage of the core version will immediately increase. If you click a few more, it will immediately exceed 100.
> 
> But we know that this is just a pure demonstration and does not even have real complex business logic code inside.

I don't know what "tab page on the left" you're talking about but this is what I see with WiceCore gallery after having clicked all around in the app. As for "real complex business logic code", this is not necessarily what takes memory.

![image](https://github.com/aelyo-softworks/Wice/assets/5328574/f23e7d39-57d6-401c-94d9-a59f3adaab85)

**Comment by sgf** [comment]
![动画06](https://github.com/aelyo-softworks/Wice/assets/2557696/4fa97f00-134a-42c3-bd25-0127f5a586ca)

**Comment by sgf** [comment]
![动画07](https://github.com/aelyo-softworks/Wice/assets/2557696/c73c5efa-7491-4f1e-b0b9-3fb67e935fe8)
and mouse select has some bug on left tab(Or Menu)

**Comment by sgf** [comment]
![动画08](https://github.com/aelyo-softworks/Wice/assets/2557696/5b667d8e-1b46-496c-b154-36427713ec55)
When the mouse wheel scrolls down, the content page moves down very slowly.

**Comment by sgf** [comment]
![动画09](https://github.com/aelyo-softworks/Wice/assets/2557696/6d485715-9ca1-4f02-b137-f9f366e900b0)
mouse characters select postion has some problem
and double click cant auto select word

**Comment by sgf** [comment]
at last gif,(mouse characters select postion has some problem)

Haven't you noticed that the position of the selected character is always behind the starting point where the mouse pointer falls (1-2 letters)?

**Comment by sgf** [comment]
"and mouse select has some bug on left tab(Or Menu)"

Didn't you notice that when switching to the second tab (Or Menu), the animation is displayed I clicked multiple times, but the second menu did not switch successfully?

**Comment by sgf** [comment]
As for the memory usage, I tried to click on all the functions. Since the complete gif is too large and requires 99mb, I reduced its size.

**Comment by smourier** [comment]
> at last gif,(mouse characters select postion has some problem)
> 
> Haven't you noticed that the position of the selected character is always behind the starting point where the mouse pointer falls (1-2 letters)?

Ok I've fixed this one in the last commit https://github.com/aelyo-softworks/Wice/commit/c38e6771bf8a88f146529fdd7884966353989682#

**Comment by smourier** [comment]
> "and mouse select has some bug on left tab(Or Menu)"
> 
> Didn't you notice that when switching to the "Collections" tab (Or Menu), the animation is displayed I clicked multiple times, but the "Collections" menu did not switch successfully? When I moved the mouse slightly and clicked again, I successfully switched to the new menu.

Not sure exactly what your problem is but I think you're clicking on the tooltip which doesn't click through.

**Comment by sgf** [comment]
> > "and mouse select has some bug on left tab(Or Menu)"
> > Didn't you notice that when switching to the "Collections" tab (Or Menu), the animation is displayed I clicked multiple times, but the "Collections" menu did not switch successfully? When I moved the mouse slightly and clicked again, I successfully switched to the new menu.
> 
> Not sure exactly what your problem is but I think you're clicking on the tooltip which doesn't click through.

Each yellow flash represents a click.
I re-edited the animation. This is an occasional bug. It does not trigger every switch.
But it will affect the experience.

![动画10](https://github.com/aelyo-softworks/Wice/assets/2557696/a11c31ee-a4d8-4d2f-a696-baeb3ace4e30)

**Comment by sgf** [comment]
![动画12](https://github.com/aelyo-softworks/Wice/assets/2557696/b22add07-d716-4a20-bd3e-97f60f86bf94)
And this seems to be related to the "Is Mouse In Pointer Enable" feature

**Comment by smourier** [comment]
Yes, it's because this setting generates WM_POINTERxxx message, to be added to the usual mouse messages (which in turns will possibly activate actions and transform the visual tree), so it causes more memory allocations when you move a mouse that will go away when GC runs (in debug builds you press F11 which calls GC.Collect()). The effect is quite attenuated in release builds.
