### ISSUE TITLE
AOT Publish System.NotSupportedException: COM Interop requires ComWrapper instance registered for marshalling.

### ISSUE THREAD

**Issue by sgf** [aelyo-softworks/Wice#11]
.net 8+ Aot+ trim
and total is too large(near 60mb)

got Error:
System.NotSupportedException: COM Interop requires ComWrapper instance registered for marshalling

![image](https://github.com/aelyo-softworks/Wice/assets/2557696/f0618773-e826-40c3-b252-11bf05595206)

**Comment by sgf** [comment]
An experimental project (not using winform, using D2D, using PublishLzmaCompressed)

![image](https://github.com/aelyo-softworks/Wice/assets/2557696/899d77d7-2146-4449-be87-23f4f4e5d8d1)

![image](https://github.com/aelyo-softworks/Wice/assets/2557696/d1df7f8c-d92f-477d-b1db-b0eb93c4f3da)

**Comment by smourier** [comment]
Wice (and DirectN below) are using COM extensively and are not AOT friendly for many reasons, the first one being they still support .NET Framework. And they don't require unsafe-marked code.

Migrating both projects would require a complete rewrite which is not planned today.

**Comment by sgf** [comment]
ok,tks

**Comment by sgf** [comment]
![image](https://github.com/aelyo-softworks/Wice/assets/2557696/15cefd7a-3de2-49c6-984d-4bc3fddf0b40)
Today, I noticed that I had done some testing before. Here is a picture with some aot data for reference.
