### ISSUE TITLE
The scroll bar is too slow when using the mouse wheel

### ISSUE THREAD

**Issue by Charltsing** [aelyo-softworks/Wice#15]
The scroll bar is too slow when using the mouse wheel

[1.zip](https://github.com/user-attachments/files/16915203/1.zip)

**Comment by smourier** [comment]
That's how it works today. It moves by the `ScrollViewer`'s `VerticalLineSize` property wich is set to `1` pixel per default https://github.com/aelyo-softworks/Wice/blob/main/WiceAot/ScrollViewer.cs#L15

You can press SHIFT to move it by the thumb size (see https://github.com/aelyo-softworks/Wice/blob/main/WiceAot/ScrollViewer.cs#L518) or you can set this `VerticalLineSize` value to something else to go faster.

**Comment by Charltsing** [comment]
WiceAot/ScrollViewer.cs , line 15

fix:

public static VisualProperty VerticalLineSizeProperty { get; } = 
    VisualProperty.Add(typeof(ScrollViewer), nameof(VerticalLineSize), VisualPropertyInvalidateModes.Arrange, GetFontSize());
public static VisualProperty HorizontalLineSizeProperty { get; } = 
    VisualProperty.Add(typeof(ScrollViewer), nameof(HorizontalLineSize), VisualPropertyInvalidateModes.Arrange, GetFontSize());
private static float GetFontSize() => Application.Current.ResourceManager.GetFontSize(-1);

**Comment by yoshiask** [comment]
This issue is still present in [2.2.0.1](https://github.com/aelyo-softworks/Wice/releases/tag/v2.2.0.1)

**Comment by smourier** [comment]
This is not an issue, this is how it works, but you can change it easily, as demonstrated here

**Comment by Charltsing** [comment]
> This issue is still present in [2.2.0.1](https://github.com/aelyo-softworks/Wice/releases/tag/v2.2.0.1)

set
sv.HorizontalLineSize = 81;
sv.VerticalLineSize = 81;
