### ISSUE TITLE
Do Wice support high DPI ?

### ISSUE THREAD

**Issue by Charltsing** [aelyo-softworks/Wice#4]
I try 125% dpi , use Wice.Samples.Gallery

![125dpi](https://github.com/aelyo-softworks/Wice/assets/19963715/57c85160-dfe5-4fbd-9127-1ffd90e127f4)

**Comment by smourier** [comment]
Wice kinda support Hi-Dpi in a sense that it doesn't honor it... ie: Windows and content are not resized proportionnally.

I don't have that issue though, here is a screenshot at 175%

![image](https://github.com/aelyo-softworks/Wice/assets/5328574/b6ceb620-678c-4a53-82ba-43a52475cbe1)

**Comment by Charltsing** [comment]
i try 175% dpi ,use Wice.Samples.Gallery.exe , Its richtextbox control displays incorrectly

my os is Windows 10 22h2

[175dpi.zip](https://github.com/aelyo-softworks/Wice/files/13173226/175dpi.zip)

**Comment by smourier** [comment]
I really can't reproduce that, here's a screenshot of my screen in 175% (w/o any DPI override applied on Wice):

![image](https://github.com/aelyo-softworks/Wice/assets/5328574/07cefdea-40e4-4dc8-aec2-d7827bca68d5)

My windows is also Windows 10 22H2 OS build 19045.3570

**Comment by Charltsing** [comment]
I know the cause of the problem now，need to modify advanced scaling settings

[cause.zip](https://github.com/aelyo-softworks/Wice/files/13179515/cause.zip)

So, how to make the software compatible with this setting?

**Comment by smourier** [comment]
That settings still doesn't change anything for me:

on:
![image](https://github.com/aelyo-softworks/Wice/assets/5328574/8f76ed47-b501-4a97-bfd6-4331ed270dbc)

off:
![image](https://github.com/aelyo-softworks/Wice/assets/5328574/070a3331-787e-404e-ae42-110bb7a5df99)

**Comment by Charltsing** [comment]
Could you please send me the exe file and all dll files you are currently executing ?
so that I can test and see if there are any differences in the file.

send to liucq@163.com or charltsing@gmail.com

thinks a lot

**Comment by smourier** [comment]
I have updated the Releases section https://github.com/aelyo-softworks/Wice/releases

**Comment by Charltsing** [comment]
i test windows 10, restart 100~125 dpi,  problem is still present.
[win10 100~125dpi.zip](https://github.com/aelyo-softworks/Wice/files/13186818/win10.100.125dpi.zip)

**Comment by Charltsing** [comment]
Why is the width of RTB different?

Fix scaling for apps setting is On or Off

![11](https://github.com/aelyo-softworks/Wice/assets/19963715/e5940de1-2fb7-4b31-881d-56212f273efc)

**Comment by Charltsing** [comment]
https://learn.microsoft.com/zh-cn/dotnet/desktop/winforms/high-dpi-support-in-windows-forms
I found that setting DpiAwareness and EnableWindowsFormsHighDpiAutoResizing in app. config has no effect on Wice(Disable app.manifest).

Maybe the winform controls such as RichTextBox should not be used in Wice
![app config](https://github.com/aelyo-softworks/Wice/assets/19963715/959183ab-8b22-46cc-b926-7ebc969a391a)
![app manifest](https://github.com/aelyo-softworks/Wice/assets/19963715/f37d0de6-5ba3-4ad0-a26b-09201d3300e5)

**Comment by smourier** [comment]
RichTextBox is not a Winforms control. Wice has no dependency over Winforms (except in some place for clipboard methods since there's no other way on Windows then use clipboard API, and Winforms wraps them easily).

The Wice RichTextBox visual does have a dependency on Windows' richedit (text services) implemented by msftedit.dll (https://learn.microsoft.com/en-us/windows/win32/api/textserv/nf-textserv-createtextservices). RTF rendering is far from being easy to implement in pure .NET.

```
[C:\]filever c:\Windows\System32\msftedit.dll
Language        0x0409 (English (United States))
CharSet         0x04b0 Unicode
CompanyName     Microsoft Corporation
FileDescription Rich Text Edit Control, v8.5
InternalName    MsftEdit
OriginalFilenam MsftEdit.DLL.MUI
ProductName     Microsoft« Windows« Operating System
ProductVersion  10.0.19041.1
FileVersion     10.0.19041.1 (WinBuild.160101.0800)
LegalCopyright  ⌐ Microsoft Corporation. All rights reserved.

Fixed File Info (VS_FIXEDFILEINFO) for c:\Windows\System32\msftedit.dll
        Signature:      feef04bd
        Struc Ver:      00010000
        FileVer:        00060002:4a610e34 (6.2:19041.3636)
        ProdVer:        000a0000:4a610e34 (10.0:19041.3636)
        FlagMask:       0000003f
        Flags:          00000000
        OS:             00040004 NT Win32
        FileType:       00000002 Dll
        SubType:        00000000
        FileDate:       00000000:00000000
```

**Comment by Charltsing** [comment]
it is msftedit.dll in my os
![捕获](https://github.com/aelyo-softworks/Wice/assets/19963715/397993fd-d144-4596-bc53-3eef4dad4219)
[msftedit.zip](https://github.com/aelyo-softworks/Wice/files/13194211/msftedit.zip)

**Comment by smourier** [comment]
I've tested with your msftedit (riched*.dll are not used they are legacy binaries) and it sill works:

![image](https://github.com/aelyo-softworks/Wice/assets/5328574/b0b44086-b45a-40af-9e94-788d74391524)

**Comment by Charltsing** [comment]
I install a english Windows10 22H2 (download from microsoft site, 2023.5.5), and insatll all online hotfix in a new PC, but  problem is still present.

Start windows with 125% dpi( default Settings for Windows 10), run Wice.Samples.Gallery, after install hotfix finished
I didn't do anything except above

![2](https://github.com/aelyo-softworks/Wice/assets/19963715/e8dd0bec-f7e2-4994-a280-7e5c5739e532)

so, i think  maybe something have been missed

**Comment by smourier** [comment]
I've made a small change to the code (https://github.com/aelyo-softworks/Wice/commit/1e39a2bf7f5d2f37b75c1261665b6aa1b23b897c), bit of a shot in the dark since I've difficulties to reproduce the problem.

**Comment by Charltsing** [comment]
it works fine (150%DPI, Fix scaling for apps setting on) in my pc, thanks a lot!

<img width="670" alt="捕获" src="https://github.com/aelyo-softworks/Wice/assets/19963715/cd86c461-bd38-4d70-afa3-7be06c909f5b">
