### ISSUE TITLE
Wice.Samples.Gallery.exe is hang up, when resize windows by mouse

### ISSUE THREAD

**Issue by Charltsing** [aelyo-softworks/Wice#6]
Wice.Samples.Gallery.exe is hang up, when resize windows by mouse (slowly move)

but if i press ctrl-shift-esc call Task Manager , this hang up is release

[hangup when rezise.zip](https://github.com/aelyo-softworks/Wice/files/13197487/hangup.when.rezise.zip)

**Comment by smourier** [comment]
This should have been fixed by the latest update https://github.com/aelyo-softworks/Wice/commit/6bb2cbdbc4c88ad574a2d775d68c922a896857ab

**Comment by Charltsing** [comment]
thinks a lot, it works fine.
