### ISSUE TITLE
Flex layout support. Universal layout container  support (like div).

### ISSUE THREAD

**Issue by sgf** [aelyo-softworks/Wice#8]
Flex layout support. Universal layout container  support (like div).
I have many years of experience in Web and winform development.
I think winform's own layout container and even WPF's layout system are very backward compared to the web's layout system.
This makes it very difficult for winform to implement some slightly complex dynamic layouts.

**Comment by smourier** [comment]
Hi,

Is there a question?

**Comment by sgf** [comment]
It's certainly not a problem, it's just a suggestion. But it doesn't seem to be very welcome, so I'll close it.
